(package "block-travel"
         "0.1.0"
         "Move to previous/next blank line")

(website-url "https://github.com/jcs-elpa/elenv")
(keywords "convenience")

(package-file "block-travel.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "jcs-elpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
